# Generated by Django 2.2.2 on 2019-06-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HireCorporateSocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirecorporate',
            name='service',
            field=models.CharField(choices=[('corporate', 'corporate'), ('social', 'social')], max_length=20),
        ),
    ]
